### ISSUE TITLE
How to use cssnano in this loader?

### ISSUE THREAD

**Issue by karantin2020** [cssnext/cssnext-loader#13]
Hello. I'm new in webpack. Could you describe how to use cssnano in this loader? Where is minimize option?
Is this possible to make use of queries to setup most common options like compression?
Thanks

**Comment by MoOx** [comment]
Just add a cssnext entry to your config like in the README and use this option http://cssnext.io/usage/#compress

**Comment by karantin2020** [comment]
~~~
cssnext: {
    minimize: true
  },
~~~
so? It didn't help for me

**Comment by MoOx** [comment]
Do you even read my previous message? Its COMPRESS
