### ISSUE TITLE
Support of IE9

### ISSUE THREAD

**Issue by ondrasak** [cssnext/cssnext-loader#17]
Since the moment I start use the cssnext-loader the builded bunde.js does not work in IE9(and lower versions). When I skip this loader it works again.

**Comment by MoOx** [comment]
This plugin "just" transforms a string to another string.
What other loader are you using?
Can you share the error?
Did you have CSS to share that is triggering the error?

**Comment by ondrasak** [comment]
I did not get the error. It was just loading page all the time.

I use this loaders for '.css' files: style, css, cssnext
```javascript
{test: /\.css$/, loader: 'style!css!cssnext', exclude: /node_modules/}
```
when I remove cssnext-loader it works normally
```javascript
{test: /\.css$/, loader: 'style!css', exclude: /node_modules/}
```

**Comment by MoOx** [comment]
Please investigate a bit more. Saying "it was loading" without any code to help isn't helping anyone.
Maybe disable some styles to find what style is causing the issue.

**Comment by ondrasak** [comment]
I'm sorry

so finally it was not the cssnext that was causing the issue.

I have included an google font in css
```css
@import url(https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&subset=latin,latin-ext);
```
that issue occurs in IE browser version equal and less than 9 even I do not use this loader.

Thanks for your time
