### ISSUE TITLE
Variables 

### ISSUE THREAD

**Issue by jacobrask** [cssnext/cssnext-loader#21]
I'm not sure if this is by design/specification, but I do 

    import './variables.css';
    import './index.css';

from my JavaScript application, and the variables are not available in index.css. It works if I `@import` them directly from index.css.

I have one CSS file per visual component in my application and it would be nice to not have to do

    @import '../css/variables.css';
    @import '../css/custom-selectors.css';
    @import '../css/media-queries.css';

in each file, even if these files are "side effect free".

**Comment by MoOx** [comment]
We cannot share a global registry. Too dangerous. Use import in css instead or define your variables using javascript https://github.com/postcss/postcss-custom-properties#variables
