### ISSUE TITLE
Is this a cssnext-loader bug?

### ISSUE THREAD

**Issue by jasonkuhrt** [cssnext/cssnext-loader#5]
Here: ~~https://github.com/webpack/webpack/issues/722#issuecomment-71627471~~ Whoops I meant here https://github.com/webpack/webpack/issues/725#issuecomment-71614133

**Comment by bloodyowl** [comment]
have you tried to add the `.css` extension

```css
@import "./base.css";
```

**Comment by jasonkuhrt** [comment]
Doesn't seem to help:
```
ERROR in ./~/css-loader!./~/cssnext!./lib/index.css
Module build failed: Error: <css input>:3:1: Failed to find './base.css' from /Users/jasonkuhrt/projects/cloud-app-cloud-control
    in [
        /Users/jasonkuhrt/projects/cloud-app-cloud-control
    ]
```

`./lib/base` works but that doesn't make any sense at the file level. It seems that `cssnext` is poorly configured such that it doesn't have the right `in` value (see error above).

I wonder if the problem relates to the issues `rework-loader` had to overcome, wherein they say *not* to use `css-loader`:

https://github.com/aaronj1335/rework-webpack-loader

**Comment by jasonkuhrt** [comment]
Maybe this version needs to be bumped? https://github.com/cssnext/cssnext/blob/master/package.json#L49

**Comment by jasonkuhrt** [comment]
See resolution here https://github.com/webpack/webpack/issues/725#issuecomment-71663236

**Comment by MoOx** [comment]
This look like a bug (cssnext-loader or postcss-import).
If you only have one path, please use `root` option (`root: "./lib"`).

That being said, relative import without `path` or `root` options should work since cssnext-loader should provide the postcss `from` option.

**Comment by MoOx** [comment]
Good to know that cssnext works natively with webpack :D
