### ISSUE TITLE
Use peer dependencies?

### ISSUE THREAD

**Issue by jasonkuhrt** [cssnext/cssnext-loader#6]
Why are we not using peerDependencies for `cssnext`? The `*-loader` scenario seems like an appropriate use-case, no?

**Comment by MoOx** [comment]
Because this https://github.com/webpack/webpack/issues/570, this https://github.com/npm/npm/issues/5080 and this https://github.com/npm/npm/issues/6565

**Comment by jasonkuhrt** [comment]
@MoOx Right. Sigh. Feels like we don't have a good solution this way though. Heh.
